### ISSUE TITLE
List element index page throws error

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/sprout-lists#34]
Update syntax in defineSortOptions

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_31099)

**Comment by BlueElefant** [comment]
Any Updates on this?

**Comment by BenParizek** [comment]
@BlueElefant I'm working on a fix in the next major version that addresses this and several other issues that have arisen with our shared plugin features. It's taking some time but is a necessary step to get me back to a position where I can provide more timely support. I can't promise a release date yet but will update this thread once I get that out.

**Comment by samuelbirch** [comment]
any updates on this?

i'm also getting this error on the "all lists" option:
`Class 'barrelstrength\\sproutbaselists\\listtypes\\SubscriberListType' not found`

**Comment by BenParizek** [comment]
The list index page issue should be fixed in v3.2.2

@samuelbirch The error you are describing may be something else. It appears your setup may have never run a couple of migrations which should have updated that class names. The base plugin `sproutbaselists` no longer exists as of Sprout Lists v3.0.0. So my guess is that you may not have upgraded to the latest Lists v2 before upgrading to v3.

The best way to solve this may be to re-upgrade from your earlier version to the latest on v2 and then upgrade to the latest on v3 from there. Outside of that, you'll need to manually modify classnames in the `sproutlists_lists.type` and `craft_elements.type` columns.

**sproutlists_lists.type**

old: `barrelstrength\sproutlists\integrations\sproutlists\SubscriberListType`
new: `barrelstrength\sproutlists\listtypes\SubscriberList`

**craft_elements.type**

old: `barrelstrength\sproutbaselists\elements\Subscriber`
new: `barrelstrength\sproutlists\elements\Subscriber`

old: `barrelstrength\sproutlists\integrations\sproutlists\SubscriberListType`
new: `barrelstrength\sproutlists\elements\ListElement`
